services:
  php:
    build:
      context: ./docker
      target: php-dev
    depends_on:
      - mysql
    tty: true
    volumes:
      - ./:/home/php-pro
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - XDEBUG_CONFIG
      - PHP_IDE_CONFIG
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD

  nginx:
      build:
          context: ./docker
          target: nginx-dev
      depends_on:
          - php
      ports:
          - "80:80"
      volumes:
        - ./:/home/php-pro


  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: