services:
  php:
    build:
      context: ./docker
      target: php-dev
    depends_on:
      - mysql
    tty: true
    volumes:
      - ./:/home/php-pro
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_IDE_CONFIG: 'serverName=php-pro'

  nginx:
      build:
          context: ./docker
          target: nginx-dev
      depends_on:
          - php
      ports:
          - "80:80"
      volumes:
        - ./:/home/php-pro
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf


  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'aliencvsynbr'
      MYSQL_DATABASE: 'garage_db'
      MYSQL_USER: 'root'
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: